apiVersion: v1
kind: Service
metadata:
  name: swagger
  namespace: swagger
  labels:
    app: swagger
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8000
  selector:
    app: swagger
